export const CardData = [
  {
    "title": "Despicable Me",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlU9ZP6j6UO5xzOn-aUwqdSCLiCfV_RkVBqQ&s",
    "tags": ["Animation", "Comedy", "Family"],
    "rating": 7.6,
    "plot": "A criminal mastermind adopts three orphans as part of his latest scheme, but he soon finds himself changing for the better.",
    "runtime": "1h 35m",
    "type": "Animation/Comedy",
    "genre": "Animation/Comedy",
    "ratingCategory": "U",
    "cast": ["Steve Carell", "Jason Segel", "Miranda Cosgrove"]
  },
  {
    "title": "Harry Potter and the Goblet of Fire",
    "image": "https://wallpapercave.com/wp/fmb9gAQ.jpg",
    "tags": ["drama", "action", "magic"],
    "rating": 8.7,
    "plot": "Harry Potter finds himself unexpectedly entered into the Triwizard Tournament, where he must face deadly challenges.",
    "runtime": "2h 37m",
    "type": "Fantasy",
    "genre": "Fantasy/Adventure",
    "ratingCategory": "U/A 13+",
    "cast": ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"]
  },
  {
    "title": "Bhediya",
    "image": "https://static.india.com/wp-content/uploads/2022/12/bhediya.jpg",
    "tags": ["horror", "fantasy", "comedy"],
    "rating": 8.7,
    "plot": "A man gets bitten by a wolf and starts transforming into a werewolf, leading to hilarious yet eerie encounters.",
    "runtime": "2h 36m",
    "type": "Horror/Comedy",
    "genre": "Horror/Comedy",
    "ratingCategory": "U/A 16+",
    "cast": ["Varun Dhawan", "Kriti Sanon"]
  },
  {
    "title": "Venom",
    "image": "https://movie.webindia123.com/movie/2018/hollywood/april/venom/venom.jpg",
    "tags": ["action", "thriller", "sci-fi"],
    "rating": 8.7,
    "plot": "A journalist gains superpowers after bonding with an alien symbiote, but it comes at a dark cost.",
    "runtime": "1h 52m",
    "type": "Action/Sci-Fi",
    "genre": "Action/Sci-Fi",
    "ratingCategory": "U/A 16+",
    "cast": ["Tom Hardy", "Michelle Williams", "Riz Ahmed"]
  },
  {
    "title": "Avengers: Endgame",
    "image": "https://wallpapercat.com/w/full/6/6/1/119145-1280x2120-mobile-hd-avengers-wallpaper-image.jpg",
    "tags": ["Superhero", "Action", "Sci-Fi"],
    "rating": 8.4,
    "plot": "The Avengers reunite for one final stand against Thanos to restore balance to the universe.",
    "runtime": "3h 2m",
    "type": "Superhero/Action",
    "genre": "Superhero/Action",
    "ratingCategory": "U/A 13+",
    "cast": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"]
  },
  {
    "title": "Locke and Key",
    "image": "https://image.tmdb.org/t/p/original/iGP2V7WVgS4eCxLudNbG7RZIHAw.jpg",
    "tags": ["Fantasy", "Mystery", "Thriller"],
    "rating": 7.4,
    "plot": "Three siblings move into a mysterious house filled with magical keys that unlock new powers and dark secrets.",
    "runtime": "TV Series",
    "type": "Fantasy/Thriller",
    "genre": "Fantasy/Thriller",
    "ratingCategory": "U/A 13+",
    "cast": ["Darby Stanchfield", "Connor Jessup", "Emilia Jones"]
  },
  {
    "title": "Interstellar",
    "image": "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SY679_.jpg",
    "tags": ["Sci-Fi", "Adventure", "Drama"],
    "rating": 8.6,
    "plot": "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
    "runtime": "2h 49m",
    "type": "Sci-Fi/Drama",
    "genre": "Sci-Fi/Drama",
    "ratingCategory": "U/A 13+",
    "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"]
  },
  {
    "title": "The Matrix",
    "image": "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
    "tags": ["Sci-Fi", "Action", "Cyberpunk"],
    "rating": 8.7,
    "plot": "A hacker discovers the world is a simulation and joins a rebellion against its controllers.",
    "runtime": "2h 16m",
    "type": "Sci-Fi/Action",
    "genre": "Sci-Fi/Action",
    "ratingCategory": "U/A 16+",
    "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
  },
  {
    "title": "Inside Out",
    "image": "https://w0.peakpx.com/wallpaper/236/551/HD-wallpaper-inside-out-dfg-gsd-thumbnail.jpg",
    "tags": ["Animation", "Comedy", "Drama"],
    "rating": 8.1,
    "plot": "The emotions inside an 11-year-old girl's mind navigate her life changes and challenges.",
    "runtime": "1h 35m",
    "type": "Animation/Comedy",
    "genre": "Animation/Comedy",
    "ratingCategory": "U",
    "cast": ["Amy Poehler", "Phyllis Smith", "Bill Hader"]
  },
  {
    "title": "You",
    "image": "https://upload.wikimedia.org/wikipedia/en/9/98/You_Season_4.jpg",
    "tags": ["Thriller", "Drama", "Crime"],
    "rating": 7.7,
    "plot": "A charming but obsessive man goes to extreme lengths to insert himself into the lives of those he desires.",
    "runtime": "TV Series",
    "type": "Thriller/Crime",
    "genre": "Thriller/Crime",
    "ratingCategory": "U/A 16+",
    "cast": ["Penn Badgley", "Victoria Pedretti", "Elizabeth Lail"]
  },
  {
    "title": "Twilight",
    "image": "https://rukminim2.flixcart.com/image/850/1000/poster/z/p/n/twilight-edward-bella-maxi-poster-pp31637-medium-original-imadhahycdhhf42p.jpeg?q=90&crop=false",
    "tags": ["Romance", "Fantasy", "Drama"],
    "rating": 5.2,
    "plot": "A teenage girl falls in love with a vampire, leading to a forbidden romance filled with danger and supernatural elements.",
    "runtime": "2h 2m",
    "type": "Romance/Fantasy",
    "genre": "Romance/Fantasy",
    "ratingCategory": "U/A 13+",
    "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner"]
  },{
    "title": "Stranger Things",
    "image": "https://upload.wikimedia.org/wikipedia/en/b/b1/Stranger_Things_season_1.jpg",
    "tags": ["Sci-Fi", "Horror", "Thriller"],
    "rating": 8.7,
    "plot": "A group of kids uncover supernatural mysteries in their small town, leading to encounters with a secret government project and alternate dimensions.",
    "runtime": "TV Series",
    "type": "Sci-Fi/Horror",
    "genre": "Sci-Fi/Horror",
    "ratingCategory": "U/A 16+",
    "cast": ["Winona Ryder", "David Harbour", "Millie Bobby Brown"]
  }
];
